module.exports = {
    START_BOARD: '$START_BOARD',
    JOIN_BOARD: '$JOIN_BOARD',
    CLOSE_BOARD: '$CLOSE_BOARD',
    BOARD_NOT_FOUND: '$BOARD_NOT_FOUND',
    GAME_PAUSED: '$GAME_PAUSED',
    PAUSE_GAME: '$PAUSE_GAME'
}